server {
    listen 80;
    server_name gurmepet.com.tr www.gurmepet.com.tr admin.gurmepet.com.tr;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'OK - certbot dogrulama bekleniyor';
        add_header Content-Type text/plain;
    }
}